### ISSUE TITLE
E2E testing

### ISSUE THREAD

**Issue by Sharlaan** [nfq-eta/nfq-react-component#7]
Nice boilerplate

I have 2 questions:

1. What do you think about Cypress.io ?

2. Regarding Quality in general for a component, which type of testing should be used, has more "value" :
- e2e testing
- unit testing + code coverage

In theory (i'm not sure) e2e test framework sound more fitted in terms of commands ("click" "navigate" etc...) and does not requires mocking for isolation ?

**Comment by FDiskas** [comment]
1. Looks cool. I like that there is a preview window and overall good speed. In this repository I used http://codecept.io with http://codecept.io/helpers/Nightmare/
It runs electron browser (based on chrome) so it works on any os and result will be the same. To write a test case is easy.
E2E tests not only about clicking. In my opinion thous tests should be done in different browsers and OS. It's possible to do so using https://www.browserstack.com/ and it's free for opensource. It's not easy to set everything up, but for complex components it must be. For example component like https://fullcalendar.io

2. I think thous tests should be implemented both. One for unit other for User Experience tests like drag and drop / resize / clicks / scrolls and so on...
In some cases (for example component who should render geometry with svg) css regression tests needed to - example repo https://github.com/nfq-eta/css-regression-test-example
For good quality component I'm preaty shure that 85% coverage is must be. Plus all reported and fixed bug cases should be tested to. You should't get back to same issue twice. Good coverage brings less stress when refactoring something :)
In now days is popular make components in typescript or flow e.x. https://github.com/ant-design/ant-design - those components are more stable and less human mistakes in it
> sorry for bad English - hope you got my point :sweat_smile:
